import { z } from "zod";

export const DemoCardDefinition = {
  type: "DemoCard",
  schema: z.object({}).strict(),
  meta: {
    displayName: "DemoCard",
    category: "custom",
    description: "Generated by genui add-component",
    examples: ["Example"]
  }
};
