import type { SkillManifest } from "../../skills/types.js";

export const DemoSkillpackSkill: SkillManifest = {
  id: "demo-skillpack",
  name: "DemoSkillpack",
  version: "0.1.0",
  description: "Generated by genui add-skill",
  author: "genui-cli",
  categories: ["custom"],
  permissionsRequested: [],
  components: [],
  tools: [],
  suggestedPrompts: []
};
