#!/usr/bin/env node

import { mkdir, writeFile, access } from "node:fs/promises";
import path from "node:path";

function toPascalCase(input: string): string {
  return input
    .split(/[^a-zA-Z0-9]/)
    .filter((segment) => segment.length > 0)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join("");
}

function toKebabCase(input: string): string {
  return input
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
}

async function ensureWorkspaceRoot(cwd: string): Promise<void> {
  const workspaceFile = path.join(cwd, "pnpm-workspace.yaml");
  await access(workspaceFile);
}

async function ensureDir(dirPath: string): Promise<void> {
  await mkdir(dirPath, { recursive: true });
}

async function createFileIfMissing(filePath: string, content: string): Promise<"created" | "exists"> {
  try {
    await access(filePath);
    return "exists";
  } catch {
    await writeFile(filePath, content, "utf8");
    return "created";
  }
}

function componentTemplate(componentName: string): string {
  const pascalName = toPascalCase(componentName);
  return [
    "import { z } from \"zod\";",
    "",
    `export const ${pascalName}Definition = {`,
    `  type: \"${pascalName}\",`,
    "  schema: z.object({}).strict(),",
    "  meta: {",
    `    displayName: \"${pascalName}\",`,
    "    category: \"custom\",",
    "    description: \"Generated by genui add-component\",",
    "    examples: [\"Example\"]",
    "  }",
    "};",
    ""
  ].join("\n");
}

function toolTemplate(toolName: string): string {
  const constName = toolName.replace(/[^a-zA-Z0-9]/g, "_");
  return [
    "import { z } from \"zod\";",
    "",
    `export const ${constName} = {`,
    `  name: \"${toolName}\",`,
    "  inputSchema: z.object({}).strict(),",
    "  outputSchema: z.object({}).strict(),",
    "  permissions: [],",
    "  handler: async (_input: Record<string, unknown>) => ({})",
    "};",
    ""
  ].join("\n");
}

function skillTemplate(skillId: string): string {
  const constName = `${toPascalCase(skillId)}Skill`;
  return [
    "import type { SkillManifest } from \"../../skills/types.js\";",
    "",
    `export const ${constName}: SkillManifest = {`,
    `  id: \"${skillId}\",`,
    `  name: \"${toPascalCase(skillId)}\",`,
    "  version: \"0.1.0\",",
    "  description: \"Generated by genui add-skill\",",
    "  author: \"genui-cli\",",
    "  categories: [\"custom\"],",
    "  permissionsRequested: [],",
    "  components: [],",
    "  tools: [],",
    "  suggestedPrompts: []",
    "};",
    ""
  ].join("\n");
}

async function run(): Promise<void> {
  const [, , command, name] = process.argv;
  const cwd = process.cwd();

  if (!command || !name) {
    console.log("Usage: genui add-component <Name> | add-tool <name> | add-skill <id>");
    process.exit(1);
  }

  await ensureWorkspaceRoot(cwd);

  if (command === "add-component") {
    const fileName = `${toKebabCase(name)}.ts`;
    const targetDir = path.join(cwd, "packages/core/src/registry/generated-components");
    await ensureDir(targetDir);
    const filePath = path.join(targetDir, fileName);
    const result = await createFileIfMissing(filePath, componentTemplate(name));
    console.log(`${result}: ${path.relative(cwd, filePath)}`);
    return;
  }

  if (command === "add-tool") {
    const fileName = `${toKebabCase(name)}.ts`;
    const targetDir = path.join(cwd, "packages/core/src/registry/generated-tools");
    await ensureDir(targetDir);
    const filePath = path.join(targetDir, fileName);
    const result = await createFileIfMissing(filePath, toolTemplate(name));
    console.log(`${result}: ${path.relative(cwd, filePath)}`);
    return;
  }

  if (command === "add-skill") {
    const fileName = `${toKebabCase(name)}.ts`;
    const targetDir = path.join(cwd, "packages/core/src/examples/generated-skills");
    await ensureDir(targetDir);
    const filePath = path.join(targetDir, fileName);
    const result = await createFileIfMissing(filePath, skillTemplate(name));
    console.log(`${result}: ${path.relative(cwd, filePath)}`);
    return;
  }

  console.log(`Unknown command: ${command}`);
  process.exit(1);
}

run().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : "Unknown error";
  console.error(`genui failed: ${message}`);
  process.exit(1);
});
