#!/usr/bin/env node

import { mkdir, writeFile, access } from "node:fs/promises";
import path from "node:path";

function toPascalCase(input: string): string {
  return input
    .split(/[^a-zA-Z0-9]/)
    .filter((segment) => segment.length > 0)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join("");
}

function toKebabCase(input: string): string {
  return input
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
}

async function importTokens(cwd: string, filePath: string): Promise<void> {
  if (!filePath) {
    console.error("Usage: genui import-tokens <tokens.json>");
    process.exit(1);
  }
  const { readFile } = await import("node:fs/promises");
  const absPath = path.isAbsolute(filePath) ? filePath : path.join(cwd, filePath);
  const raw = await readFile(absPath, "utf-8");
  const data = JSON.parse(raw) as Record<string, unknown>;

  // Detect format: Figma Variables or Style Dictionary
  const isFigma = "collections" in data || "modes" in data;
  const isStyleDict = "color" in data || "spacing" in data;

  const tokens: Record<string, string> = {};

  if (isFigma) {
    // Figma Variables export format
    const variables = (data.variables ?? data.collections ?? data) as Record<string, unknown>;
    for (const [key, val] of Object.entries(variables)) {
      if (typeof val === "string") tokens[`--genui-${key.replace(/\//g, "-").toLowerCase()}`] = val;
    }
  } else if (isStyleDict) {
    // Style Dictionary flat format
    function flatten(obj: Record<string, unknown>, prefix: string): void {
      for (const [k, v] of Object.entries(obj)) {
        const path = prefix ? `${prefix}-${k}` : k;
        if (v && typeof v === "object" && "value" in (v as Record<string, unknown>)) {
          tokens[`--genui-${path}`] = String((v as Record<string, unknown>).value);
        } else if (v && typeof v === "object") {
          flatten(v as Record<string, unknown>, path);
        }
      }
    }
    flatten(data, "");
  } else {
    // Generic key-value
    for (const [key, val] of Object.entries(data)) {
      if (typeof val === "string") tokens[`--genui-${key}`] = val;
    }
  }

  const cssLines = [":root {", ...Object.entries(tokens).map(([k, v]) => `  ${k}: ${v};`), "}"];
  const outPath = path.join(cwd, "packages/renderer-react/src/theme/imported-tokens.css");
  await writeFile(outPath, cssLines.join("\n") + "\n");
  console.log(`Imported ${Object.keys(tokens).length} tokens → ${path.relative(cwd, outPath)}`);
}

async function ensureWorkspaceRoot(cwd: string): Promise<void> {
  const workspaceFile = path.join(cwd, "pnpm-workspace.yaml");
  await access(workspaceFile);
}

async function ensureDir(dirPath: string): Promise<void> {
  await mkdir(dirPath, { recursive: true });
}

async function createFileIfMissing(filePath: string, content: string): Promise<"created" | "exists"> {
  try {
    await access(filePath);
    return "exists";
  } catch {
    await writeFile(filePath, content, "utf8");
    return "created";
  }
}

function componentTemplate(componentName: string): string {
  const pascalName = toPascalCase(componentName);
  return [
    "import { z } from \"zod\";",
    "",
    `export const ${pascalName}Definition = {`,
    `  type: \"${pascalName}\",`,
    "  schema: z.object({}).strict(),",
    "  meta: {",
    `    displayName: \"${pascalName}\",`,
    "    category: \"custom\",",
    "    description: \"Generated by genui add-component\",",
    "    examples: [\"Example\"]",
    "  }",
    "};",
    ""
  ].join("\n");
}

function toolTemplate(toolName: string): string {
  const constName = toolName.replace(/[^a-zA-Z0-9]/g, "_");
  return [
    "import { z } from \"zod\";",
    "",
    `export const ${constName} = {`,
    `  name: \"${toolName}\",`,
    "  inputSchema: z.object({}).strict(),",
    "  outputSchema: z.object({}).strict(),",
    "  permissions: [],",
    "  handler: async (_input: Record<string, unknown>) => ({})",
    "};",
    ""
  ].join("\n");
}

function skillTemplate(skillId: string): string {
  const constName = `${toPascalCase(skillId)}Skill`;
  return [
    "import type { SkillManifest } from \"../../skills/types.js\";",
    "",
    `export const ${constName}: SkillManifest = {`,
    `  id: \"${skillId}\",`,
    `  name: \"${toPascalCase(skillId)}\",`,
    "  version: \"0.1.0\",",
    "  description: \"Generated by genui add-skill\",",
    "  author: \"genui-cli\",",
    "  categories: [\"custom\"],",
    "  permissionsRequested: [],",
    "  components: [],",
    "  tools: [],",
    "  suggestedPrompts: []",
    "};",
    ""
  ].join("\n");
}

async function run(): Promise<void> {
  const allArgs = process.argv.slice(2);
  const command = allArgs[0];
  const name = allArgs[1];
  const cwd = process.cwd();

  if (command === "dev") {
    const { spawn } = await import("node:child_process");
    const gptSpark = allArgs.includes("--gpt-spark") || allArgs.includes("-g");
    const filter = gptSpark ? "@genui/demo-host" : "*";
    console.log(`Starting dev server${gptSpark ? " (GPT Spark mode)" : ""}...`);
    const child = spawn("pnpm", ["--filter", filter, "exec", "vite", "--host", "127.0.0.1", "--port", "5173", "--open"], {
      cwd,
      stdio: "inherit",
      shell: true
    });
    child.on("exit", (code) => process.exit(code ?? 0));
    return;
  }

  if (command === "import-tokens") {
    await importTokens(cwd, name ?? "");
    return;
  }

  if (!command || !name) {
    console.log("Usage: genui add-component <Name> | add-tool <name> | add-skill <id> | dev [--gpt-spark] | import-tokens <file>");
    process.exit(1);
  }

  await ensureWorkspaceRoot(cwd);

  if (command === "add-component") {
    const fileName = `${toKebabCase(name)}.ts`;
    const targetDir = path.join(cwd, "packages/core/src/registry/generated-components");
    await ensureDir(targetDir);
    const filePath = path.join(targetDir, fileName);
    const result = await createFileIfMissing(filePath, componentTemplate(name));
    console.log(`${result}: ${path.relative(cwd, filePath)}`);
    return;
  }

  if (command === "add-tool") {
    const fileName = `${toKebabCase(name)}.ts`;
    const targetDir = path.join(cwd, "packages/core/src/registry/generated-tools");
    await ensureDir(targetDir);
    const filePath = path.join(targetDir, fileName);
    const result = await createFileIfMissing(filePath, toolTemplate(name));
    console.log(`${result}: ${path.relative(cwd, filePath)}`);
    return;
  }

  if (command === "add-skill") {
    const fileName = `${toKebabCase(name)}.ts`;
    const targetDir = path.join(cwd, "packages/core/src/examples/generated-skills");
    await ensureDir(targetDir);
    const filePath = path.join(targetDir, fileName);
    const result = await createFileIfMissing(filePath, skillTemplate(name));
    console.log(`${result}: ${path.relative(cwd, filePath)}`);
    return;
  }

  console.log(`Unknown command: ${command}`);
  process.exit(1);
}

run().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : "Unknown error";
  console.error(`genui failed: ${message}`);
  process.exit(1);
});
